#!/bin/sh
# Remove files generated by autoreconf -fi.
# For use by the clean target in debian/rules.

set -e

dh_testdir
rm -fr build-aux
rm -f ABOUT-NLS aclocal.m4 config.h.in configure
(cd po && xargs -d "\n" rm -f) < debian/generated-po.list
(cd m4 && xargs -d "\n" rm -f) < debian/generated-m4.list
find . -name Makefile.in -delete
