#!/bin/sh
# If deconfiguring, remove lzma, unlzma, lzcat symlinks for
# xz, and let the best other alternative provide those
# commands instead.
set -e

unregister_alternative() {
	update-alternatives --remove $1 /usr/bin/xz
}

case "$1" in
remove|deconfigure)
	unregister_alternative lzcat
	unregister_alternative unlzma
	unregister_alternative lzma
	;;
upgrade|failed-upgrade)
	;;
*)
	echo >&2 "prerm called with unknown argument '$1'"
	exit 0
	;;
esac
